// <auto-generated />
namespace S_SquaredEnterprices3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InserValuesIntoRoleTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InserValuesIntoRoleTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202302122155135_InserValuesIntoRoleTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
